# Generated by Django 5.2 on 2025-04-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='prompt_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='system_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
